version: "3.3"
services:
  postgresql_app:
    image: postgres:16.0
    environment:
      POSTGRES_USER: abdullah
      POSTGRES_PASSWORD: abdullah123
      POSTGRES_DB: abdullahdb
    ports:
      - "5432:5432"
    volumes:
      - "/data:/var/lib/postgresql/data"
  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "8080:8080"